DROP TABLE IF EXISTS rate_limits;
DROP TABLE IF EXISTS snapshot_cache;
DROP TABLE IF EXISTS sync_logs;
DROP TABLE IF EXISTS stock_prices;
DROP TABLE IF EXISTS basket_items;
DROP TABLE IF EXISTS indices;
